### ISSUE TITLE
Manually upload python package failed: "null value in column "version" violates not-null constraint"

### ISSUE THREAD

**Issue by Kuzyn2000** [pulp/pulp_python#719] opened 2024-08-09 06:50 UTC
**Version**
Katello 4.11.0

**Describe the bug**
Upload failed:

2024-08-07T15:50:44 [E|bac|51d128e3] null value in column "version" violates not-null constraint
 51d128e3 | DETAIL:  Failing row contains (01912d1b-33c0-7f60-96f8-5b407c22a948, apache_airflow-2.9.3-py3-none-any.whl, bdist_wheel, , null, 2.3, , <!--
 51d128e3 | Licensed to the Apache Software Foundation (ASF) under one
 51d128e3 | ..., , , , , , , , , , , , , "[]", "[]", "[]", "[]", "[]", , 4a36cb5dbd9925448ef171b72f2db0656121383e16306eded723331963d169db, , "{}"). (Katello::Errors::Pulp3Error)
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/pulp3/abstract_async_task.rb:108:in `block in check_for_errors'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/pulp3/abstract_async_task.rb:106:in `each'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/pulp3/abstract_async_task.rb:106:in `check_for_errors'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/pulp3/abstract_async_task.rb:162:in `poll_external_task'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action/polling.rb:100:in `poll_external_task_with_rescue'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action/polling.rb:22:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action/cancellable.rb:14:in `run'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/pulp3/abstract_async_task.rb:10:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:589:in `block (3 levels) in execute_run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:32:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/middleware/remote_action.rb:16:in `block in run'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/middleware/remote_action.rb:40:in `block in as_remote_user'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/models/katello/concerns/user_extensions.rb:21:in `cp_config'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/middleware/remote_action.rb:27:in `as_cp_user'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/middleware/remote_action.rb:39:in `as_remote_user'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/lib/actions/middleware/remote_action.rb:16:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/rails_executor_wrap.rb:14:in `block in run'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/execution_wrapper.rb:91:in `wrap'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/rails_executor_wrap.rb:13:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action/progress.rb:31:in `with_progress_calculation'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action/progress.rb:17:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/load_setting_values.rb:20:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_request_id.rb:15:in `block in run'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_request_id.rb:52:in `restore_current_request_id'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_request_id.rb:15:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_timezone.rb:15:in `block in run'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_timezone.rb:44:in `restore_curent_timezone'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_timezone.rb:15:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `block in run'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_taxonomies.rb:45:in `restore_current_taxonomies'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:32:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:27:in `pass'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware.rb:19:in `pass'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_user.rb:15:in `block in run'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_user.rb:54:in `restore_curent_user'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/app/lib/actions/middleware/keep_current_user.rb:15:in `run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/stack.rb:23:in `call'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/middleware/world.rb:31:in `execute'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:588:in `block (2 levels) in execute_run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:587:in `catch'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:587:in `block in execute_run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:490:in `block in with_error_handling'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:490:in `catch'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:490:in `with_error_handling'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:582:in `execute_run'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/action.rb:303:in `execute'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:18:in `block (2 levels) in execute'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/execution_plan/steps/abstract.rb:167:in `with_meta_calculation'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:17:in `block in execute'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:32:in `open_action'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:16:in `execute'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/director.rb:94:in `execute'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/executors/sidekiq/worker_jobs.rb:11:in `block (2 levels) in perform'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/executors.rb:18:in `run_user_code'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/executors/sidekiq/worker_jobs.rb:9:in `block in perform'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/executors/sidekiq/worker_jobs.rb:25:in `with_telemetry'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/executors/sidekiq/worker_jobs.rb:8:in `perform'
 51d128e3 | /usr/share/gems/gems/dynflow-1.8.2/lib/dynflow/executors/sidekiq/serialization.rb:27:in `perform'
 51d128e3 | [ sidekiq ]
 51d128e3 | [ concurrent-ruby ]
2024-08-07T15:50:47 [I|aud|51d128e3] Katello::Repository (123) update event on publication_href /pulp/api/v3/publications/python/pypi/01912d1a-d175-7645-b9ef-e68f940c3000/, /pulp/api/v3/publications/python/pypi/01912d1b-3d2b-7272-92e7-135307814490/
2024-08-07T15:50:48 [I|bac|51d128e3] Task {label: , execution_plan_id: 11ab75ac-bc7a-42f1-a9e2-4be20fa3c9db} state changed: pending 
2024-08-07T15:50:48 [I|bac|51d128e3] Task {label: Actions::Katello::Repository::CapsuleSync, id: 975c5633-b90b-47c4-a356-0d0a946d4b3c, execution_plan_id: 11ab75ac-bc7a-42f1-a9e2-4be20fa3c9db} state changed: planning 
2024-08-07T15:50:48 [I|bac|51d128e3] Task {label: Actions::Katello::Repository::CapsuleSync, id: 975c5633-b90b-47c4-a356-0d0a946d4b3c, execution_plan_id: 11ab75ac-bc7a-42f1-a9e2-4be20fa3c9db} state changed: planned 
2024-08-07T15:50:48 [I|bac|51d128e3] Task {label: Actions::Katello::Repository::CapsuleSync, id: 975c5633-b90b-47c4-a356-0d0a946d4b3c, execution_plan_id: 11ab75ac-bc7a-42f1-a9e2-4be20fa3c9db} state changed: running 
2024-08-07T15:50:48 [I|bac|51d128e3] Task {label: Actions::Katello::Repository::CapsuleSync, id: 975c5633-b90b-47c4-a356-0d0a946d4b3c, execution_plan_id: 11ab75ac-bc7a-42f1-a9e2-4be20fa3c9db} state changed: stopped  result: success
2024-08-07T15:50:48 [I|bac|51d128e3] Task {label: Actions::Katello::Repository::UploadFiles, id: 6ed03a4c-da04-4999-9733-5eaebce31dc2, execution_plan_id: a609fef8-c46d-4250-8555-34aefedd8296} state changed: stopped  result: warning
2024-08-07T15:50:49 [E|app|51d128e3] ForemanTasks::TaskError: Task 6ed03a4c-da04-4999-9733-5eaebce31dc2: Katello::Errors::Pulp3Error: null value in column "version" violates not-null constraint
 51d128e3 | DETAIL:  Failing row contains (01912d1b-33c0-7f60-96f8-5b407c22a948, apache_airflow-2.9.3-py3-none-any.whl, bdist_wheel, , null, 2.3, , <!--
 51d128e3 | Licensed to the Apache Software Foundation (ASF) under one
 51d128e3 | ..., , , , , , , , , , , , , "[]", "[]", "[]", "[]", "[]", , 4a36cb5dbd9925448ef171b72f2db0656121383e16306eded723331963d169db, , "{}").
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/lib/foreman_tasks.rb:56:in `block in sync_task'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/lib/foreman_tasks.rb:55:in `tap'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/lib/foreman_tasks.rb:55:in `sync_task'
 51d128e3 | /usr/share/gems/gems/foreman-tasks-9.0.4/lib/foreman_tasks/triggers.rb:22:in `sync_task'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/controllers/katello/api/v2/repositories_controller.rb:467:in `upload_content'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/base.rb:228:in `process_action'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/rendering.rb:30:in `process_action'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 51d128e3 | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 51d128e3 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 51d128e3 | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 51d128e3 | /usr/share/gems/gems/audited-5.4.2/lib/audited/sweeper.rb:16:in `around'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 51d128e3 | /usr/share/gems/gems/audited-5.4.2/lib/audited/sweeper.rb:16:in `around'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:137:in `run_callbacks'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/callbacks.rb:41:in `process_action'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/rescue.rb:22:in `process_action'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 51d128e3 | /usr/share/gems/gems/activerecord-6.1.7.8/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/app/controllers/katello/concerns/api/api_controller.rb:46:in `process_action'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/base.rb:165:in `process'
 51d128e3 | /usr/share/gems/gems/actionview-6.1.7.8/lib/action_view/rendering.rb:39:in `process'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal.rb:190:in `dispatch'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal.rb:254:in `dispatch'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:49:in `serve'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `each'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `serve'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:842:in `call'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/engine.rb:539:in `call'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `public_send'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `method_missing'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:49:in `serve'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `each'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `serve'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:842:in `call'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/lib/katello/middleware/organization_created_enforcer.rb:18:in `call'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/lib/katello/middleware/event_daemon.rb:10:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/apipie-dsl-2.6.1/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 51d128e3 | /usr/share/gems/gems/apipie-rails-1.2.3/lib/apipie/static_dispatcher.rb:68:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 51d128e3 | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 51d128e3 | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 51d128e3 | /usr/share/gems/gems/apipie-rails-1.2.3/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/tempfile_reaper.rb:15:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/etag.rb:27:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/conditional_get.rb:40:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 51d128e3 | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:266:in `context'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:260:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/cookies.rb:697:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:98:in `run_callbacks'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/rack/logger.rb:37:in `call_app'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/rack/logger.rb:28:in `call'
 51d128e3 | /usr/share/gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 51d128e3 | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 51d128e3 | /usr/share/gems/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 51d128e3 | /usr/share/gems/gems/katello-4.11.1/lib/katello/prevent_json_parsing.rb:12:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'
 51d128e3 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/executor.rb:14:in `call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/ssl.rb:77:in `call'
 51d128e3 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 51d128e3 | /usr/share/gems/gems/secure_headers-6.5.0/lib/secure_headers/middleware.rb:11:in `call'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/engine.rb:539:in `call'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `public_send'
 51d128e3 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `method_missing'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/urlmap.rb:74:in `block in call'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `each'
 51d128e3 | /usr/share/gems/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `call'
 51d128e3 | /usr/share/gems/gems/puma-6.4.0/lib/puma/configuration.rb:272:in `call'
 51d128e3 | /usr/share/gems/gems/puma-6.4.0/lib/puma/request.rb:100:in `block in handle_request'
 51d128e3 | /usr/share/gems/gems/puma-6.4.0/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
 51d128e3 | /usr/share/gems/gems/puma-6.4.0/lib/puma/request.rb:99:in `handle_request'
 51d128e3 | /usr/share/gems/gems/puma-6.4.0/lib/puma/server.rb:443:in `process_client'
 51d128e3 | /usr/share/gems/gems/puma-6.4.0/lib/puma/server.rb:241:in `block in run'
 51d128e3 | /usr/share/gems/gems/puma-6.4.0/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
 51d128e3 | /usr/share/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2024-08-07T15:50:49 [I|app|51d128e3] Completed 500 Internal Server Error in 43677ms (Views: 0.3ms | ActiveRecord: 131.0ms | Allocations: 136357)

**To Reproduce**
Create product, create python type repo, manually upload this package:
apache_airflow-2.9.3-py3-none-any.whl
urllib3-2.2.2-py3-none-any.whl
fsspec-2024.6.1-py3-none-any.whl
httpcore-1.0.5-py3-none-any.whl

**Expected behavior**
Upload successful.

**Additional context**
https://community.theforeman.org/t/upload-python-package-apache-airflow-2-9-3-py3-none-any-whl-katello-null-value-in-column-version-violates-not-null-constraint/39031

**Comment by gerrod3** [comment] 2024-08-09 13:59
This issue is a duplicate of https://github.com/pulp/pulp_python/issues/682. I think we can backport this to pulp_python 3.11, but we currently don't support pulp_python 3.10. Looking at the requirements I think katello 4.11 should be using pulp_python 3.11 since it is the more recent version that still supports pulpcore 3.39.

**Comment by AndersBennedsgaard** [comment] 2024-08-26 08:06
I have set up pull-through caching towards PyPI, and when I try to run `pip install polars` I get `null value in column "version" of relation "python_pythonpackagecontent" violates not-null constraint` from PostgreSQL and the Pulp content app logs. Is this caused by the same constraint, or should I create a new issue about this?

**Comment by gerrod3** [comment] 2024-08-26 12:58
Probably, which version of pulp_python are you on?

**Comment by AndersBennedsgaard** [comment] 2024-08-26 17:02
Version 3.12.1

**Comment by gerrod3** [comment] 2024-08-26 17:10
Ahh I see. The fix is on main, but not on the 3.12 branch. I only backported it to 3.11. Let me fix that.

**Comment by AndersBennedsgaard** [comment] 2024-08-27 08:13
Thanks for the quick release :+1: 
I guess this issue can be closed, if the original problem has been resolved?

**Comment by gerrod3** [comment] 2024-08-28 15:39
Yes I think this can be closed. It is fixed on main and in 3.11.3 and 3.12.3. We don't have any other supported branches, so everyone else must upgrade to one of these minimum versions.

**Closed by gerrod3** 2024-08-28 15:39 UTC
Labels: Issue
