### ISSUE TITLE
Cannot upload package without version

### ISSUE THREAD

**Issue by maximiliankolb** [pulp/pulp_python#723] opened 2024-08-12 06:53 UTC
**Version**
* Foreman 3.11
* Katello 4.13
* pulpcore 3.49.15
* pulp_python 3.11.1

**Describe the bug**
If you try to upload a package from pypi.org without a version, the upload fails.

**To Reproduce**
* Download https://files.pythonhosted.org/packages/f2/52/bac9f8a7cf28d7f9d57712ac26dc47936f9b3d55ab547d9c083ed255a27d/apache_airflow-2.9.3-py3-none-any.whl
* on Foreman+Katello: create product + empty repo
* Upload package from your local machine to Foreman via WebUI

**Expected behavior**
* Upload works

**Additional context**
* pypi.org accepts this package
* you can install the package via pip locally
* more info: [Foreman Community Forum](https://community.theforeman.org/t/upload-python-package-apache-airflow-2-9-3-py3-none-any-whl-katello-null-value-in-column-version-violates-not-null-constraint/39031?u=maximilian)

Relevant Foreman production log:

````
2024-08-12T08:41:41 [E|bac|5dd92ec0] null value in column "version" of relation "python_pythonpackagecontent" violates not-null constraint
 5dd92ec0 | DETAIL:  Failing row contains (01914552-2e9e-751f-b0e2-e4a0da55736a, apache_airflow-2.9.3-py3-none-any.whl, bdist_wheel, , null, 2.3, , <!--
 5dd92ec0 | Licensed to the Apache Software Foundation (ASF) under one
 5dd92ec0 | ..., , , , , , , , , , , , , "[]", "[]", "[]", "[]", "[]", , 4a36cb5dbd9925448ef171b72f2db0656121383e16306eded723331963d169db, , "{}"). (Katello::Errors::Pulp3Error)
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/pulp3/abstract_async_task.rb:108:in `block in check_for_errors'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/pulp3/abstract_async_task.rb:106:in `each'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/pulp3/abstract_async_task.rb:106:in `check_for_errors'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/pulp3/abstract_async_task.rb:162:in `poll_external_task'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action/polling.rb:100:in `poll_external_task_with_rescue'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action/polling.rb:22:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action/cancellable.rb:15:in `run'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/pulp3/abstract_async_task.rb:10:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:590:in `block (3 levels) in execute_run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:33:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/middleware/remote_action.rb:16:in `block in run'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/middleware/remote_action.rb:40:in `block in as_remote_user'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/models/katello/concerns/user_extensions.rb:21:in `cp_config'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/middleware/remote_action.rb:27:in `as_cp_user'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/middleware/remote_action.rb:39:in `as_remote_user'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/lib/actions/middleware/remote_action.rb:16:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/rails_executor_wrap.rb:14:in `block in run'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/execution_wrapper.rb:91:in `wrap'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/rails_executor_wrap.rb:13:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action/progress.rb:29:in `with_progress_calculation'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action/progress.rb:15:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/load_setting_values.rb:20:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_request_id.rb:15:in `block in run'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_request_id.rb:52:in `restore_current_request_id'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_request_id.rb:15:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_timezone.rb:15:in `block in run'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_timezone.rb:44:in `restore_curent_timezone'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_timezone.rb:15:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `block in run'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_taxonomies.rb:45:in `restore_current_taxonomies'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:33:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:28:in `pass'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware.rb:20:in `pass'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_user.rb:15:in `block in run'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_user.rb:54:in `restore_curent_user'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_user.rb:15:in `run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/stack.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/middleware/world.rb:31:in `execute'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:589:in `block (2 levels) in execute_run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:588:in `catch'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:588:in `block in execute_run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:491:in `block in with_error_handling'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:491:in `catch'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:491:in `with_error_handling'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:583:in `execute_run'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/action.rb:304:in `execute'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:18:in `block (2 levels) in execute'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/execution_plan/steps/abstract.rb:168:in `with_meta_calculation'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:17:in `block in execute'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:32:in `open_action'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:16:in `execute'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/director.rb:95:in `execute'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:12:in `block (2 levels) in perform'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/executors.rb:18:in `run_user_code'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:10:in `block in perform'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:26:in `with_telemetry'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:9:in `perform'
 5dd92ec0 | /usr/share/gems/gems/dynflow-1.8.4/lib/dynflow/executors/sidekiq/serialization.rb:28:in `perform'
 5dd92ec0 | [ sidekiq ]
 5dd92ec0 | [ concurrent-ruby ]
2024-08-12T08:41:44 [I|aud|5dd92ec0] Katello::Repository (123) update event on publication_href /pulp/api/v3/publications/python/pypi/01914551-382c-7fe0-ae8d-0450fa07e87d/, /pulp/api/v3/publications/python/pypi/01914552-4013-78f4-b651-0f7eb0faff6d/
2024-08-12T08:41:47 [I|bac|5dd92ec0] Task {label: , execution_plan_id: ea4a836d-adbb-4542-b99c-032a4a77c0d6} state changed: pending 
2024-08-12T08:41:47 [I|bac|5dd92ec0] Task {label: Actions::Katello::Repository::CapsuleSync, id: 925a6f62-ec70-4cb7-8100-611293cd9bc6, execution_plan_id: ea4a836d-adbb-4542-b99c-032a4a77c0d6} state changed: planning 
2024-08-12T08:41:48 [I|bac|5dd92ec0] Task {label: Actions::Katello::Repository::CapsuleSync, id: 925a6f62-ec70-4cb7-8100-611293cd9bc6, execution_plan_id: ea4a836d-adbb-4542-b99c-032a4a77c0d6} state changed: planned 
2024-08-12T08:41:48 [I|bac|5dd92ec0] Task {label: Actions::Katello::Repository::CapsuleSync, id: 925a6f62-ec70-4cb7-8100-611293cd9bc6, execution_plan_id: ea4a836d-adbb-4542-b99c-032a4a77c0d6} state changed: running 
2024-08-12T08:41:48 [I|bac|5dd92ec0] Task {label: Actions::Katello::Repository::CapsuleSync, id: 925a6f62-ec70-4cb7-8100-611293cd9bc6, execution_plan_id: ea4a836d-adbb-4542-b99c-032a4a77c0d6} state changed: stopped  result: success
2024-08-12T08:41:48 [I|bac|5dd92ec0] Task {label: Actions::Katello::Repository::UploadFiles, id: d9d1a806-925e-48ab-ac74-a64ab5a66b34, execution_plan_id: 6ea7338c-4c9e-4002-b78d-61166fed2142} state changed: stopped  result: warning
2024-08-12T08:41:49 [E|app|5dd92ec0] ForemanTasks::TaskError: Task d9d1a806-925e-48ab-ac74-a64ab5a66b34: Katello::Errors::Pulp3Error: null value in column "version" of relation "python_pythonpackagecontent" violates not-null constraint
 5dd92ec0 | DETAIL:  Failing row contains (01914552-2e9e-751f-b0e2-e4a0da55736a, apache_airflow-2.9.3-py3-none-any.whl, bdist_wheel, , null, 2.3, , <!--
 5dd92ec0 | Licensed to the Apache Software Foundation (ASF) under one
 5dd92ec0 | ..., , , , , , , , , , , , , "[]", "[]", "[]", "[]", "[]", , 4a36cb5dbd9925448ef171b72f2db0656121383e16306eded723331963d169db, , "{}").
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/lib/foreman_tasks.rb:56:in `block in sync_task'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/lib/foreman_tasks.rb:55:in `tap'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/lib/foreman_tasks.rb:55:in `sync_task'
 5dd92ec0 | /usr/share/gems/gems/foreman-tasks-9.1.1/lib/foreman_tasks/triggers.rb:22:in `sync_task'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/controllers/katello/api/v2/repositories_controller.rb:461:in `upload_content'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/base.rb:228:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/rendering.rb:30:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 5dd92ec0 | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 5dd92ec0 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 5dd92ec0 | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 5dd92ec0 | /usr/share/gems/gems/audited-5.6.0/lib/audited/sweeper.rb:16:in `around'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 5dd92ec0 | /usr/share/gems/gems/audited-5.6.0/lib/audited/sweeper.rb:16:in `around'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:137:in `run_callbacks'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/callbacks.rb:41:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/rescue.rb:22:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/activerecord-6.1.7.8/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/app/controllers/katello/concerns/api/api_controller.rb:46:in `process_action'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/abstract_controller/base.rb:165:in `process'
 5dd92ec0 | /usr/share/gems/gems/actionview-6.1.7.8/lib/action_view/rendering.rb:39:in `process'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal.rb:190:in `dispatch'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_controller/metal.rb:254:in `dispatch'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:49:in `serve'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `each'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `serve'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:842:in `call'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/engine.rb:539:in `call'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `public_send'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `method_missing'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/mapper.rb:49:in `serve'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `each'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in `serve'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:842:in `call'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/lib/katello/middleware/organization_created_enforcer.rb:18:in `call'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/lib/katello/middleware/event_daemon.rb:10:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/apipie-dsl-2.6.2/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 5dd92ec0 | /usr/share/gems/gems/apipie-rails-1.3.0/lib/apipie/static_dispatcher.rb:74:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/static.rb:24:in `call'
 5dd92ec0 | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 5dd92ec0 | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 5dd92ec0 | /usr/share/gems/gems/apipie-rails-1.3.0/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb:15:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/etag.rb:27:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/conditional_get.rb:40:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/head.rb:12:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 5dd92ec0 | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:266:in `context'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:260:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/cookies.rb:697:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:98:in `run_callbacks'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/rack/logger.rb:37:in `call_app'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/rack/logger.rb:28:in `call'
 5dd92ec0 | /usr/share/gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 5dd92ec0 | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 5dd92ec0 | /usr/share/gems/gems/katello-4.13.1/lib/katello/prevent_json_parsing.rb:12:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/method_override.rb:24:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/runtime.rb:22:in `call'
 5dd92ec0 | /usr/share/gems/gems/activesupport-6.1.7.8/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/executor.rb:14:in `call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/sendfile.rb:110:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/ssl.rb:77:in `call'
 5dd92ec0 | /usr/share/gems/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 5dd92ec0 | /usr/share/gems/gems/secure_headers-6.5.0/lib/secure_headers/middleware.rb:11:in `call'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/engine.rb:539:in `call'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `public_send'
 5dd92ec0 | /usr/share/gems/gems/railties-6.1.7.8/lib/rails/railtie.rb:207:in `method_missing'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
 5dd92ec0 | /usr/share/gems/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
 5dd92ec0 | /usr/share/gems/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
 5dd92ec0 | /usr/share/gems/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
 5dd92ec0 | /usr/share/gems/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
 5dd92ec0 | /usr/share/gems/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
 5dd92ec0 | /usr/share/gems/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
 5dd92ec0 | /usr/share/gems/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
 5dd92ec0 | /usr/share/gems/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
 5dd92ec0 | /usr/share/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2024-08-12T08:41:49 [I|app|5dd92ec0] Completed 500 Internal Server Error in 62321ms (Views: 0.3ms | ActiveRecord: 124.0ms | Allocations: 153952)
````

**Comment by gerrod3** [comment] 2024-08-12 12:58
Closing since it's a duplicate of #719, which is technically a duplicate of #682.

**Closed by gerrod3** 2024-08-12 12:58 UTC
Labels: Triage-Needed, Issue
